"""create employee tables

Revision ID: 850830ab3d57
Revises: fd556354f5eb
Create Date: 2026-09-14 20:55:26.378304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850830ab3d57'
down_revision: Union[str, Sequence[str], None] = 'fd556354f5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('compensation_type', sa.String(length=20), nullable=False),
    sa.Column('compensation_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_business_id'), 'employees', ['business_id'], unique=False)
    op.create_table('employee_financial_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_financial_events_employee_id'), 'employee_financial_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_financial_events_event_date'), 'employee_financial_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_employee_financial_events_event_type'), 'employee_financial_events', ['event_type'], unique=False)
    op.create_table('employee_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_notes_employee_id'), 'employee_notes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_notes_note_date'), 'employee_notes', ['note_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_notes_note_date'), table_name='employee_notes')
    op.drop_index(op.f('ix_employee_notes_employee_id'), table_name='employee_notes')
    op.drop_table('employee_notes')
    op.drop_index(op.f('ix_employee_financial_events_event_type'), table_name='employee_financial_events')
    op.drop_index(op.f('ix_employee_financial_events_event_date'), table_name='employee_financial_events')
    op.drop_index(op.f('ix_employee_financial_events_employee_id'), table_name='employee_financial_events')
    op.drop_table('employee_financial_events')
    op.drop_index(op.f('ix_employees_business_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
