import uuid
from datetime import UTC, date, datetime
from decimal import Decimal

from sqlalchemy import (
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from ledger.db.base import Base


class MonthlyReportClosing(Base):
    __tablename__ = "monthly_report_closings"

    __table_args__ = (
        UniqueConstraint(
            "business_id",
            "year",
            "month",
            name="uq_monthly_report_closing_business_month",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    business_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    year: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    month: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    bank_balance: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
    )

    closing_expense: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
    )

    is_closed: Mapped[bool] = mapped_column(
        nullable=False,
        default=False,
    )

    closed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
    )


class DailyReportClosing(Base):
    """
    Stores the accounting review/closing state for a single business day.

    A daily report can be closed only after the relevant accounting
    sections have been reviewed.

    The closing stores a fingerprint of the underlying accounting state
    at the time of closing. If sales, expenses, employee records, or
    other data contributing to the daily report change afterwards, the
    current fingerprint will no longer match the stored fingerprint and
    the closing can be treated as stale.

    Closing a day does NOT lock the underlying accounting data.
    """

    __tablename__ = "daily_report_closings"

    __table_args__ = (
        UniqueConstraint(
            "business_id",
            "report_date",
            name="uq_daily_report_closing_business_date",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    business_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    report_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        index=True,
    )

    # Fingerprint representing the accounting state that was reviewed
    # when this day was closed.
    #
    # The actual fingerprint is generated by the Reports service from
    # the underlying sales, expenses, and employee accounting data.
    #
    # If the underlying data changes, the current fingerprint will differ
    # from this value and the closing becomes stale.
    accounting_fingerprint: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
    )

    # Optional note recorded when the day is closed.
    note: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    is_closed: Mapped[bool] = mapped_column(
        nullable=False,
        default=False,
    )

    closed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
    )